// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtvyxv3uGQ2EE7rvDWeohUR6KQTv_7aRM',
    appId: '1:955287370402:web:c8fbd6df83ec921e97f5fb',
    messagingSenderId: '955287370402',
    projectId: 'fitness-7aeda',
    authDomain: 'fitness-7aeda.firebaseapp.com',
    storageBucket: 'fitness-7aeda.appspot.com',
    measurementId: 'G-SGKPEVDK5R',
    databaseURL: 'https://fitness-7aeda-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-fhtZJxcwJxyelsXz3VHwqxxNqeZ-Eos',
    appId: '1:955287370402:android:80d01eb1c285e69397f5fb',
    messagingSenderId: '955287370402',
    projectId: 'fitness-7aeda',
    storageBucket: 'fitness-7aeda.appspot.com',
    databaseURL: 'https://fitness-7aeda-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmbISq_HJvipc1IfrCdOGgrHm7PundWk8',
    appId: '1:955287370402:ios:652e229436d5405797f5fb',
    messagingSenderId: '955287370402',
    projectId: 'fitness-7aeda',
    storageBucket: 'fitness-7aeda.appspot.com',
    iosClientId: '955287370402-jqbs4tdkgsup165qsec61ks26vjh0rri.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
    databaseURL: 'https://fitness-7aeda-default-rtdb.europe-west1.firebasedatabase.app/'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmbISq_HJvipc1IfrCdOGgrHm7PundWk8',
    appId: '1:955287370402:ios:652e229436d5405797f5fb',
    messagingSenderId: '955287370402',
    projectId: 'fitness-7aeda',
    storageBucket: 'fitness-7aeda.appspot.com',
    iosClientId: '955287370402-jqbs4tdkgsup165qsec61ks26vjh0rri.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
    databaseURL: 'https://fitness-7aeda-default-rtdb.europe-west1.firebasedatabase.app/'
  );
}
